//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Frm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class N4_logToUserOperation:ModelBase
    {
        public Nullable<int> Id { get; set; }
        public string User_unique_id { get; set; }
        public string Prd_user_name { get; set; }
        public string Column_path { get; set; }
        public string Operation_name { get; set; }
        public string Operation_desc { get; set; }
        public string Exception_desc { get; set; }
        public string Event_level { get; set; }
        public Nullable<System.DateTime> Create_time { get; set; }
        public byte[] Last_timestamp { get; set; }
    }
}
