//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Frm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class N4_SysDatOriManageModeSet:ModelBase
    {
        public Nullable<int> Id { get; set; }
        public string UniqueId { get; set; }
        public string Mode { get; set; }
        public string Value { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DataStatus { get; set; }
        public Nullable<bool> AbandonStatus { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Create_time { get; set; }
        public string Last_updater { get; set; }
        public Nullable<System.DateTime> Last_update_time { get; set; }
        public string Approver { get; set; }
        public Nullable<System.DateTime> Approve_time { get; set; }
        public string Abandoner { get; set; }
        public Nullable<System.DateTime> Abandon_time { get; set; }
        public Nullable<System.DateTime> Last_timestamp { get; set; }
    }
}
