//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Frm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_N4_Department:ModelBase
    {
        public Nullable<int> Id { get; set; }
        public string Organization_uniqueid { get; set; }
        public string Organization_code { get; set; }
        public string Name { get; set; }
        public string Brief_name { get; set; }
        public string Description { get; set; }
        public string Mnemonic_code { get; set; }
        public string Manager_uniqueid { get; set; }
        public string Prd_manager_name { get; set; }
        public string Parent_organization_uniqueid { get; set; }
        public string Parent_organization_name { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Data_status { get; set; }
        public Nullable<bool> Abandon_status { get; set; }
        public string Creator_uniqueid { get; set; }
        public string Prd_creator_name { get; set; }
        public Nullable<System.DateTime> Create_time { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> Update_time { get; set; }
        public string Submitter { get; set; }
        public Nullable<System.DateTime> Submit_time { get; set; }
        public string Approver { get; set; }
        public Nullable<System.DateTime> Approve_time { get; set; }
        public string Abandoner { get; set; }
        public Nullable<System.DateTime> Abandon_time { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public byte[] Last_timestamp { get; set; }
    }
}
