//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Frm.Template4
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_common
    {
        public int id { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public string thread { get; set; }
        public string log_level { get; set; }
        public string logger { get; set; }
        public string message { get; set; }
        public string exception { get; set; }
        public string entity_scheme_name { get; set; }
        public string entity_id { get; set; }
        public string string_for_old_entity { get; set; }
        public string string_for_new_entity { get; set; }
        public string description { get; set; }
        public string device_info { get; set; }
        public string userid { get; set; }
    }
}
