//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Frm.Template4
{
    using System;
    using System.Collections.Generic;
    
    public partial class N4_DepartmentPrivilege
    {
        public int id { get; set; }
        public string department_uniqueid { get; set; }
        public string privilege_code { get; set; }
        public string prd_privilege_text { get; set; }
        public System.DateTime create_time { get; set; }
        public bool is_deleted { get; set; }
        public byte[] last_timestamp { get; set; }
    }
}
