//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Frm.Template4
{
    using System;
    using System.Collections.Generic;
    
    public partial class N4_logToUserLoginout
    {
        public int id { get; set; }
        public string user_unique_id { get; set; }
        public string prd_user_name { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public string login_type { get; set; }
        public string device_info { get; set; }
        public string event_level { get; set; }
        public string exception_desc { get; set; }
        public byte[] last_timestamp { get; set; }
    }
}
