//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Frm.Template4
{
    using System;
    using System.Collections.Generic;
    
    public partial class N4_SysDatOriManageModeSet
    {
        public int Id { get; set; }
        public string UniqueId { get; set; }
        public string Mode { get; set; }
        public string Value { get; set; }
        public string Remark { get; set; }
        public int DataStatus { get; set; }
        public bool AbandonStatus { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string last_updater { get; set; }
        public Nullable<System.DateTime> last_update_time { get; set; }
        public string approver { get; set; }
        public Nullable<System.DateTime> approve_time { get; set; }
        public string abandoner { get; set; }
        public Nullable<System.DateTime> abandon_time { get; set; }
        public Nullable<System.DateTime> last_timestamp { get; set; }
    }
}
