//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Frm.Template4
{
    using System;
    using System.Collections.Generic;
    
    public partial class N4_SysDatRole
    {
        public int id { get; set; }
        public string unique_id { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string Dir { get; set; }
        public string role_desc { get; set; }
        public string creator_uniqueid { get; set; }
        public string creator_name { get; set; }
        public System.DateTime create_time { get; set; }
        public string updator_uniqueid { get; set; }
        public string updator_name { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string submitter_uniqueid { get; set; }
        public string submitter_name { get; set; }
        public Nullable<System.DateTime> submit_time { get; set; }
        public string approver_uniqueid { get; set; }
        public string approver_name { get; set; }
        public Nullable<System.DateTime> approver_time { get; set; }
        public string abandoner_uniqueid { get; set; }
        public string abandoner_name { get; set; }
        public Nullable<System.DateTime> abandon_time { get; set; }
        public string data_status { get; set; }
        public Nullable<bool> abandon_status { get; set; }
        public bool is_deleted { get; set; }
        public byte[] last_timestamp { get; set; }
    }
}
