//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Frm.Template4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_N4_DataPrivilege_Templete
    {
        public int id { get; set; }
        public string data_view_name { get; set; }
        public string data_view_code { get; set; }
        public string columns_of_view { get; set; }
        public string description_of_view { get; set; }
        public bool is_deleted { get; set; }
        public System.DateTime create_time { get; set; }
        public decimal last_timestamp { get; set; }
    }
}
